version: "3.8"

services:
  mongo-database:
    image: mongo
    container_name: "user-database"
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: users

networks:
  backend:

volumes:
  mongo-data: