mongock:
  change-logs-scan-package:
    - com.filos.users.repository.migrations

spring:
  data:
    mongodb:
      username: useraccount
      password: secretPasssword
      database: users
      host: localhost
      port: 27017
      auto-index-creation: true

