GET localhost:8080/movies/60abcd0b6de8c847bcfe66c2

###

POST localhost:8080/movies
Content-Type: application/json

{
  "imdbId": "122",
  "title": "test title",
  "overview": "some overview",
  "tagline": "dafsfsf",
  "originalTitle": null,
  "homepage": "http://localhost",
  "originalLanguage": "en",
  "popularity": 144.2,
  "budget": 237000000,
  "revenue": 1999,
  "releaseDate": "2009-12-10"
}

###
GET localhost:8080/movies/search?text=test
Content-Type: application/json
Accept: application/json