version: "3.8"

services:
  elasticsearch-database:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: "search-database"
    ports:
      - "9200:9200"
    networks:
      - backend
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
networks:
  backend: