server:
  port: 9090

info:
  app:
    name: ${spring.application.name}
eureka:
  client:
    service-url:

      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: false
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
debug: true
logging:
  level:
    org:
      springframework:
        web: TRACE
spring:
  application:
    name: gateway

