POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username2",
  "password": "some secret password",
  "email": "email2@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-14T145655.400.json

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username2",
  "password": "some secret password",
  "email": "email2@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-14T131404.500.json

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-14T131224.500.json

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-14T131054.500.json

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-14T130826.500.json

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-14T130228.500.json

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-14T004721.201.json

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-14T003052.201.json

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-14T000252.201.json

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-13T235659.500.json

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-13T235451.400.json

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-13T235130.400.json

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-13T235042.400.json

###

POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "test username",
  "password": "some secret password",
  "email": "email@email.com",
  "firstName": "First",
  "lastName": "Last Name",
  "dateOfBirth": "2021-02-13"
}

<> 2021-02-13T234451.400.json

###

