version: "3.8"



services:
  mongo-database:
    image: mongo
    container_name: "user-database"
    volumes:
      - mongo-data-dev:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
      MONGO_INITDB_DATABASE: users

volumes:
  mongo-data-dev:
